# MAINTAINER: errorfatal89@gmail.com
version: '3'
services:
  tinyurl:
    image: fofcn/tinyurl:latest
    restart: always
    ports:
      - "53000:53000"
    environment:
      - SERVER_PORT=53000
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/tiny_urldb?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      - SPRING_DATASOURCE_USERNAME=tinyurl_user
      - SPRING_DATASOUCE_PASSWORD=Yy123456

  redis:
    image: redis:4

  mysql:
    image: mysql:5.7
    ports:
      - "53001:3306"
    volumes:
      - "./docker/mysql/volume:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
      MYSQL_DATABASE: "tiny_urldb"
      MYSQL_USER: "tinyurl_user"
      MYSQL_PASSWORD: "Yy123456"
